### ISSUE TITLE
Corrupted codebase

### ISSUE THREAD

**Issue by AmirMEdris** [AhmetMuratAcar/DNA-Comparer#3]
This projects structure isnt MLA and upon pulling I get WHEA_UNCONTROLLABLE_ERROR. You dont have to fix the issue but Id take a pc.

**Comment by AhmetMuratAcar** [comment]
GET A JOB RAHHHHHHHHHHHHHH
![RAHH](https://github.com/AhmetMuratAcar/DNA-Comparer/assets/58138778/24db36c4-cfb9-4ded-8c02-7b2c142d3204)
