### ISSUE TITLE
DNA comparison tool not working

### ISSUE THREAD

**Issue by msyuksel** [AhmetMuratAcar/DNA-Comparer#4]
Description: I am trying to use the DNA comparison tool but it is not working. When I open the application, the GUI appears but when I try to load a DNA sequence file, nothing happens. I have tried loading different files and restarting the application but the issue persists.

Steps to reproduce:

Open the DNA comparison tool.
Click on “Load file” button.
Select a DNA sequence file.
Observe that nothing happens.
Expected behavior: The selected DNA sequence file should be loaded and displayed in the application.

Actual behavior: Nothing happens when a DNA sequence file is selected.

Environment:

Operating system: Windows 10
Python version: 3.9.7
DNA comparison tool version: 1.0

**Comment by msyuksel** [comment]
Just a heads up, we need to get this issue resolved before release next Monday!

**Comment by AhmetMuratAcar** [comment]
![nerdge](https://github.com/AhmetMuratAcar/DNA-Comparer/assets/58138778/aa8f353b-0a18-496d-99c3-62c2e2986800)
