### ISSUE TITLE
DNA-Comparer fails to compare DNA sequences with different lengths

### ISSUE THREAD

**Issue by msyuksel** [AhmetMuratAcar/DNA-Comparer#5]
Description: I tried to use the DNA-Comparer tool to compare two DNA sequences with different lengths, but the tool gave me an error message saying “The length of the sequences must be equal”. I expected the tool to be able to handle sequences with different lengths and perform a pairwise alignment or a global alignment. Is this a bug or a limitation of the tool?

Steps to reproduce:

Download and install the DNA-Comparer tool from [the GitHub repository](https://www.gedmatch.com/applications/one-to-many/).
Run the tool with the following command: python dna_comparer.py -s1 ATCGATCG -s2 ATCGATCGATCG
Observe the error message: “The length of the sequences must be equal”
Expected behavior: The tool should be able to compare DNA sequences with different lengths and output a similarity score and an alignment.

Actual behavior: The tool fails to compare DNA sequences with different lengths and gives an error message.

Environment: Windows 10, Python 3.9, DNA-Comparer version 1.0

Screenshots: Attached a screenshot of the error message.

Additional information: I tried to compare DNA sequences with different lengths using other tools such as [One-to-Many DNA Comparison](https://support.ancestry.com/s/article/DNA-compare?language=en_US) from GEDmatch and [DNA compare] from Ancestry, and they worked fine. I think this is a feature that DNA-Comparer should have as well.

**Comment by AhmetMuratAcar** [comment]
Skill issue
